updated log message and included remove device mapper links code

diff --git a/usr/sbin/lvmsnapshot b/usr/sbin/lvmsnapshot
--- a/usr/sbin/lvmsnapshot
+++ b/usr/sbin/lvmsnapshot
@@ -1,7 +1,7 @@
 #!/bin/bash
 #
 # LVM Snapshot & Mount Script
-# Version 0.4
+# Version 0.5beta
 
 # Copyright (c) 2011 Mathias Geat <mathias@ailoo.net>
 # with additions by Felix Moche <felix@moches.de>
@@ -24,8 +24,10 @@
 # Changelog
 #=====================================================================
 #
-# ver 0.5       (2013-03-29)
+# ver 0.5beta       (2013-03-29)
 #	- Added switch to  create snapshot without mounting
+#	- Added remove device mapper links
+#	- Added scriptname to log messages
 #
 # ver 0.4       (2013-03-29)
 #       - Added lvmsnapshot identifer switch
@@ -128,6 +130,7 @@ GREP=/bin/grep
 WC=/usr/bin/wc
 RM=/bin/rm
 KPARTX=/sbin/kpartx
+DMSETIP=/sbin/dmsetup
 
 #=====================================================================
 # Set up shell
@@ -190,12 +193,12 @@ function checkmount {
 }
 
 function checkvolume {
-    outputne "Checking availability of volume..."
+    outputne "lvmsnapshot: Checking availability of volume..."
 
     $LVDISPLAY $@ > /dev/null 2>&1
     if [ $? -ne 0  ]; then
         status_error "failed"
-        error "Volume '$VOLUMEPATH' does not exist."
+        error "lvmsnapshot: Volume '$VOLUMEPATH' does not exist."
 
     else
         status_success "ok"
@@ -216,7 +219,7 @@ function checksnapshot {
 }
 
 function cleanup {
-    outputne "Deleting mount directory at $MOUNTPOINT..."
+    outputne "lvmsnapshot: Deleting mount directory at $MOUNTPOINT..."
     $RM -rf $MOUNTPOINT
 
     if [ $? -eq 0 ]; then
@@ -401,12 +404,12 @@ fi
 #=====================================================================
 
 if [ -z $1 ]; then
-    echo_error "Please specify a command.\n"
+    echo_error "lvmsnapshot: Please specify a command.\n"
     usage $EXIT_ERROR
 fi
 
 if [ -z $2 ]; then
-    echo_error "Please specify a volume name.\n"
+    echo_error "lvmsnapshot: Please specify a volume name.\n"
     usage $EXIT_ERROR
 fi
 
@@ -459,17 +462,17 @@ if [ $1 = "create" ]; then
     #=====================================================================
     # Create Snapshot
     #=====================================================================
-    outputne "Creating snapshot..."
+    outputne "lvmsnapshot: Creating snapshot..."
     status_success "ok"
     $LVCREATE -L $SNAPSHOTSIZE -s -n $SNAPSHOTNAME $VOLUMEPATH > /dev/null 2>&1
 
     if  $MOUNTSNAP ; then 
-    outputne "Checking if mountpoint is mounted..."
+    outputne "lvmsnapshot: Checking if mountpoint is mounted..."
 
     checkmount $MOUNTPOINT
     if [ $? -eq 0 ]; then
         status_error "yes"
-        error "Mountpoint is mounted. Please unmount and re-run."
+        error "lvmsnapshot: Mountpoint is mounted. Please unmount and re-run."
     else
         status_success "no"
     fi
@@ -478,38 +481,38 @@ if [ $1 = "create" ]; then
         status_success "ok"
 
         if [[ $MODE == "block" ]]; then
-            outputne "Mapping snapshot partitions..."
+            outputne "lvmsnapshot: Mapping snapshot partitions..."
             $KPARTX -a $SNAPSHOTPATH > /dev/null 2>&1
 
             if [ $? -eq 0 ]; then
                 status_success "ok"
 
                 if [ -b $MAPPEDPATH ]; then
-                    status_success "Found mapped device."
+                    status_success "lvmsnapshot: Found mapped device."
                 else
-                    error "Could not find mapped device"
+                    error "lvmsnapshot: Could not find mapped device"
                 fi
             else
                 status_error "failed"
-                error "Error while mapping block device partitions."
+                error "lvmsnapshot: Error while mapping block device partitions."
             fi
         fi
 
         if [ -d $MOUNTPOINT ]; then
-            output "Mount directory exists, ommiting mkdir."
+            output "lvmsnapshot: Mount directory exists, ommiting mkdir."
         else
-            outputne "Creating mountpoint directory..."
+            outputne "lvmsnapshot: Creating mountpoint directory..."
 
             mkdir -p $MOUNTPOINT > /dev/null 2>&1
             if [ $? -eq 0 ]; then
                 status_success "ok"
             else
                 status_error "failed"
-                error "Error while creating mountpoint directory."
+                error "lvmsnapshot: Error while creating mountpoint directory."
             fi
         fi
 
-        outputne "Mounting snapshot..."
+        outputne "lvmsnapshot: Mounting snapshot..."
 
         if [[ $MODE == "block" ]]; then
             $MOUNT $MAPPEDPATH $MOUNTPOINT > /dev/null 2>&1
@@ -523,14 +526,14 @@ if [ $1 = "create" ]; then
         else
             status_error "failed"
             cleanup
-            error "Error while mounting snapshot."
+            error "lvmsnapshot: Error while mounting snapshot."
         fi
     else
         status_error "failed"
-        error "Error while creating snapshot."
+        error "lvmsnapshot: Error while creating snapshot."
     fi
 else
-	outputne "Mounted snapshot..."
+	outputne "lvmsnapshot: Mounted snapshot..."
 	status_success "no"
 fi
 
@@ -540,55 +543,62 @@ elif [ $1 = "remove" ]; then
     # Remove Snapshot
     #=====================================================================
 
-    outputne "Checking if mountpoint is mounted..."
+    outputne "lvmsnapshot: Checking if mountpoint is mounted..."
 
     checkmount $MOUNTPOINT
     if [ $? -eq 0 ]; then
         status_success "yes"
-        outputne "Unmounting snapshot..."
+        outputne "lvmsnapshot: Unmounting snapshot..."
         $UMOUNT $MOUNTPOINT > /dev/null 2>&1
     	cleanup
     else
 	status_success "ok"
-	outputne  "Snapshot not mounted continuing..."
+	outputne  "lvmsnapshot: Snapshot not mounted continuing..."
 	status_success "ok"
     fi
     
-    outputne "Checking if snapshot exists... $SNAPSHOTPATH ..." 	
+    outputne "lvmsnapshot: Checking if snapshot exists... $SNAPSHOTPATH ..." 	
     checksnapshot $SNAPSHOTPATH
     if [ $? -eq 0 ]; then
         #status_success "yes"
 
         if [[ $MODE == "block" ]]; then
-            outputne "Unmapping snapshot partitions..."
+            outputne "lvmsnapshot: Unmapping snapshot partitions..."
             $KPARTX -d $SNAPSHOTPATH > /dev/null 2>&1
 
             if [ $? -eq 0 ]; then
                 status_success "ok"
             else
                 status_error "failed"
-                error "Error while unmapping block device partitions."
+                error "lvmsnapshot: Error while unmapping block device partitions."
             fi
         fi
 
-        
+	outputne "lvmsnapshot: Remove snapshot devmapper links ...  $SNAPSHOTPATH ..."
+	$DMSETUP remove $SNAPSHOTPATH > /dev/null 2>&1
+	if [ $? -eq 0 ]; then
+            status_success "ok"
+        else
+            status_error "failed"
+            error "lvmsnapshot: Error while removing snapshot using dmsetup, please remove manually. $DMSETUP remove $SNAPSHOTPATH ... "
+        fi        
 
-        outputne "Removing snapshot..."
+        outputne "lvmsnapshot: Removing snapshot..."
         $LVREMOVE -f $SNAPSHOTPATH > /dev/null 2>&1
 
         if [ $? -eq 0 ]; then
             status_success "ok"
         else
             status_error "failed"
-            error "Error while removing snapshot, please remove manually."
+            error "lvmsnapshot: Error while removing snapshot, please remove manually."
         fi
     else
+        error "Error lvmsnapshot: while removing  snapshot."
         status_error "failed"
-        error "Error while removing  snapshot."
-    fi
+     fi
 
 else
-    error "Unknown command: $1"
+    error "lvmsnapshot: Unknown command: $1"
     echo
     usage $EXIT_ERROR
 fi
