removed device mapper code

diff --git a/usr/sbin/lvmsnapshot b/usr/sbin/lvmsnapshot
--- a/usr/sbin/lvmsnapshot
+++ b/usr/sbin/lvmsnapshot
@@ -26,7 +26,6 @@
 #
 # ver 0.5beta       (2013-03-29)
 #	- Added switch to  create snapshot without mounting
-#	- Added remove device mapper links
 #	- Added scriptname to log messages
 #
 # ver 0.4       (2013-03-29)
@@ -575,13 +574,13 @@ elif [ $1 = "remove" ]; then
         fi
 
 	outputne "lvmsnapshot: Remove snapshot devmapper links ...  $SNAPSHOTPATH ..."
-	$DMSETUP remove $SNAPSHOTPATH > /dev/null 2>&1
-	if [ $? -eq 0 ]; then
-            status_success "ok"
-        else
-            status_error "failed"
-            error "lvmsnapshot: Error while removing snapshot using dmsetup, please remove manually. $DMSETUP remove $SNAPSHOTPATH ... "
-        fi        
+	#$DMSETUP remove $SNAPSHOTPATH > /dev/null 2>&1
+	#if [ $? -eq 0 ]; then
+        #    status_success "ok"
+        #else
+        #    status_error "failed"
+        #    error "lvmsnapshot: Error while removing snapshot using dmsetup, please remove manually. $DMSETUP remove $SNAPSHOTPATH ... "
+        #fi
 
         outputne "lvmsnapshot: Removing snapshot..."
         $LVREMOVE -f $SNAPSHOTPATH > /dev/null 2>&1
